Repository marmotitude/s3-tester, pull requests merged in 2024-04, with the labels that each got.

#22 doc: how to use it from aio oci image
  README.md
  oci/README.md
Labels: pr:ship

#23 feat: add jq in the tools image
  oci/tools.Containerfile
Labels: pr:ship

#26 make scheduled tests more flexible by using env vars
  .github/workflows/manual-test.yml
  .github/workflows/scheduled-tests.yml
Labels: pr:ship

#30 rename schedule test to fix syntax error
  .github/workflows/scheduled-tests.yml
Labels: pr:ship

#29 simpler support for shellspec extra args on test.sh
  README.md
  test.sh
Labels: pr:show

#35 mgccli updated to 0.18.5
  oci/tools.Containerfile
Labels: pr:ship

#37 feat: update mgc cli to 0.18.6-rc3
  oci/tools.Containerfile
Labels: pr:ship

#34 document how to run tests from Github workers
  .github/workflows/README.md
  README.md
Labels: pr:ship

#39 build: support option to skip known issues
  .github/workflows/docker-image.yml
  .github/workflows/manual-test.yml
  .github/workflows/scheduled-tests.yml
  spec/002_bucket-name-validation_spec.sh
  spec/020_access-the-public-bucket-and-check-the-access-of-objects_spec.sh
  spec/known_issues.sh
Labels: pr:ship

#40 fix: add support to mgc profile on tests 5, 6, 7, 8
  spec/002_bucket-name-validation_spec.sh
Labels: pr:ship

#41 Adjust 2 6 7
  .github/workflows/manual-test.yml
  spec/002_bucket-name-validation_spec.sh
  spec/known_issues.sh
Labels: pr:ship

#43 add color to manual tests
  .github/workflows/manual-test.yml
  .github/workflows/scheduled-tests.yml
Labels: pr:show

#44 fix: mgc acl set now use --dst instead of --bucket
  spec/023_create-a-acl-read-for-a-bucket_spec.sh
  spec/026_create-acl-read-write-for-a-bucket_spec.sh
  spec/027_create-acl-in-a-batch-for-more-than-2-ppl-with-option-of-R-and-R-Wdifferents_spec.sh
Labels: pr:ship

#45 build: update mgc to version 0.18.6
  oci/tools.Containerfile
Labels: pr:ship

#46 adicionado template para aceitar vhost style
  profiles.example.yaml
  templates/aws/config
Labels: pr:ask
